"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# ✅ Cargar variables del archivo .env (solo local)
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ SECRET KEY
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-i5%#q45(&lrdi0@=2n^o_3@nyjwq*d+@&4jx+pi7w-#1v2zajt"
)

# ✅ DEBUG (en Render debe ser False)
# Acepta: "1", "true", "True", "TRUE"
DEBUG = os.environ.get("DEBUG", "0").lower() in ("1", "true", "yes")

# ✅ Render hostname automático (para ALLOWED_HOSTS)
RENDER_HOST = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

# ✅ ALLOWED_HOSTS
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]

# Si Render te da hostname, lo añadimos
if RENDER_HOST:
    ALLOWED_HOSTS.append(RENDER_HOST)

# Si no hay nada, por seguridad deja vacío o localhost en dev
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# ✅ CSRF para Render
CSRF_TRUSTED_ORIGINS = []
if RENDER_HOST:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_HOST}")

# ==========================================================
# ✅ Apps
# ==========================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cv",
]

# ==========================================================
# ✅ Middleware
# ==========================================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ✅ WhiteNoise
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ==========================================================
# ✅ DATABASE (Postgres en Render)
# ==========================================================
DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    # ✅ Si no hay DATABASE_URL, usa SQLite (para que NO reviente y de 500)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }

# ==========================================================
# ✅ Password validation
# ==========================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==========================================================
# ✅ Internationalization
# ==========================================================
LANGUAGE_CODE = "es-ec"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ==========================================================
# ✅ Static & Media
# ==========================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
