# Generated by Django 6.0.1 on 2026-01-29 21:01

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_alter_ventagarage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosacademicos',
            name='fecharecurso',
            field=models.DateField(blank=True, null=True, validators=[cv.models.fecha_no_futura]),
        ),
    ]
